const SLUMS = [
 
 {
  "SLUM_ID": 1,
  "SLUM_NAME": "Shiv nandi nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Keshobag",
  "Area": 41296.616976,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 2,
  "SLUM_NAME": "Islampura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 66573.932403,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 3,
  "SLUM_NAME": "Janak Taal (Kushwaha mohalla)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 14998.679424,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 4,
  "SLUM_NAME": "Ramaji ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 15619.490543,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 5,
  "SLUM_NAME": "Gram bara",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bara",
  "Area": 97399.486635,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 6,
  "SLUM_NAME": "Jatav pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Shankarpur",
  "Area": 120050.987622,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 7,
  "SLUM_NAME": "Bees Sutriya nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 1,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 18510.017072,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 8,
  "SLUM_NAME": "Kachi sarae ghosipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 9726.45443,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 9,
  "SLUM_NAME": "Shivnagar Ghosipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 50383.958835,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 10,
  "SLUM_NAME": "Sunar ki Bagia",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 7970.252176,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 11,
  "SLUM_NAME": "Panchsheel nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 4294.991947,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 12,
  "SLUM_NAME": "Jaduwala Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 5648.77384,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 13,
  "SLUM_NAME": " Shindhiya nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 15918.914356,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 14,
  "SLUM_NAME": " Rampuri mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 20187.988637,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 15,
  "SLUM_NAME": " Ambedkar nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 2,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Ranipura",
  "Area": 3038.479336,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 16,
  "SLUM_NAME": "Ghosipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 3,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 20669.155872,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 17,
  "SLUM_NAME": " Farrash khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 3,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 22697.346286,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 18,
  "SLUM_NAME": " Shiv nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 3,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 5313.26193,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 19,
  "SLUM_NAME": "Ramghad",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 3,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 18053.428384,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 21,
  "SLUM_NAME": "Indra Colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Keshobag A.B. Road",
  "Area": 31563.495126,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 22,
  "SLUM_NAME": "Mevati mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Village Bahodapur",
  "Area": 31943.61269,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 23,
  "SLUM_NAME": "Banda Ghura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bulbul pura",
  "Area": 61120.156882,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 24,
  "SLUM_NAME": "Ghatampur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghatampur",
  "Area": 7353.377734,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 25,
  "SLUM_NAME": "Mirja pur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghatampur",
  "Area": 11028.209408,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 26,
  "SLUM_NAME": "Bulbul pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Village Bulbul pura",
  "Area": 4486.038127,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 27,
  "SLUM_NAME": "Chandra nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 4,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghatampur",
  "Area": 14812.195186,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 28,
  "SLUM_NAME": "Badnapura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 5,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Shankarpur",
  "Area": 17589.239652,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 29,
  "SLUM_NAME": "Reshampura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 5,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Akabarpur",
  "Area": 117044.362151,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 30,
  "SLUM_NAME": "Damodar Bagh Colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 5,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Damodar Bagh",
  "Area": 30716.798101,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 31,
  "SLUM_NAME": " krishna nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 5,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Malanpur",
  "Area": 152812.060718,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 32,
  "SLUM_NAME": " Kishan bag (A.B.ROAD)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 5,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kishan bag",
  "Area": 56402.383215,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 33,
  "SLUM_NAME": "Mangleswar Road",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 23242.044248,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 34,
  "SLUM_NAME": "Josyana Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 25602.692822,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 35,
  "SLUM_NAME": "Ladhedi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 50983.626691,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 36,
  "SLUM_NAME": "Mevati mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 12517.21795,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 37,
  "SLUM_NAME": "Haveli pichbada",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 19921.764353,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 38,
  "SLUM_NAME": "Jhasi Ganj",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 6790.710458,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 39,
  "SLUM_NAME": "Jhajir katra",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 30524.862804,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 40,
  "SLUM_NAME": " Machii Addi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 6,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 26060.458142,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 41,
  "SLUM_NAME": "Jagna Pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 49497.885055,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 42,
  "SLUM_NAME": "Indra Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 48177.430042,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 43,
  "SLUM_NAME": "Madan pura (Madan kui )",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 2759.848288,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 44,
  "SLUM_NAME": "Lootpura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 37610.271364,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 45,
  "SLUM_NAME": " Sharma farm no.2",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Swaje form",
  "Area": 6925.366549,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 46,
  "SLUM_NAME": " Sharma farm no.3",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 7,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 5740.221824,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 47,
  "SLUM_NAME": "Chodae ke Hanuman",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 8,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 53407.181513,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 48,
  "SLUM_NAME": "Narsingh Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 8,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 44384.064421,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 49,
  "SLUM_NAME": " Sharma farm no.1",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 8,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Swaje form",
  "Area": 9924.812968,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 50,
  "SLUM_NAME": "Ranipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 86643.536291,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 51,
  "SLUM_NAME": "Rangiana Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 48503.474517,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 52,
  "SLUM_NAME": "Posthi Khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 10186.002807,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 53,
  "SLUM_NAME": "Golpade",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 12811.575506,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 54,
  "SLUM_NAME": "Raja Mandi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 103934.362549,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 55,
  "SLUM_NAME": "Soda ka Kua",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 6697.692995,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 56,
  "SLUM_NAME": "Maddi ka Bazar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 9847.858558,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 57,
  "SLUM_NAME": "Maidai Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 9,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 11589.539105,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 58,
  "SLUM_NAME": "Golandaj",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 39152.488595,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 59,
  "SLUM_NAME": "Keshobagh",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 24765.884218,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 60,
  "SLUM_NAME": "Aau Khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 9874.831777,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 61,
  "SLUM_NAME": "Jama Maszid Chowk Bazar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 7939.449442,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 62,
  "SLUM_NAME": "Kasi naresh ki gali",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Ranipura",
  "Area": 11971.715825,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 63,
  "SLUM_NAME": "Sunar mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Ranipura",
  "Area": 8112.997269,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 64,
  "SLUM_NAME": "Kanoon goyan",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana kala",
  "Area": 12182.348249,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 65,
  "SLUM_NAME": "Tameshwar mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gram Jaganapura",
  "Area": 3310.326773,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 66,
  "SLUM_NAME": " Hatha khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 10,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ahukhana",
  "Area": 5548.166581,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 67,
  "SLUM_NAME": "Goshpura No 1",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 11,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 8998.764152,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 68,
  "SLUM_NAME": "Goshpura No2",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 11,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 10106.54079,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 69,
  "SLUM_NAME": "Rasula Bad",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 12,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 6498.93399,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 70,
  "SLUM_NAME": "Kotawala Mohalla ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 13,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 3725.253232,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 71,
  "SLUM_NAME": "Pachee Pada ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 13,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 5409.714142,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 72,
  "SLUM_NAME": "Khidki Mohalla ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 13,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 1458.390436,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 73,
  "SLUM_NAME": " Horipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 13,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 7693.775344,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 74,
  "SLUM_NAME": "Gudri",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana khurd",
  "Area": 4606.725144,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 75,
  "SLUM_NAME": "Noorganj",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana khurd",
  "Area": 13684.031318,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 76,
  "SLUM_NAME": "Kwaja Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 15371.48289,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 77,
  "SLUM_NAME": "Ramtapura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 51019.429081,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 78,
  "SLUM_NAME": " Khwaja kanooun",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ramtapura",
  "Area": 24760.702221,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 79,
  "SLUM_NAME": "Jati ki Lane",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 15,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 20487.984667,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 80,
  "SLUM_NAME": "Harizan Basti ( LINE NO.5)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 15,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 8965.55558,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 81,
  "SLUM_NAME": " New sanjay nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 15,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gadhaipura",
  "Area": 60220.823158,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 82,
  "SLUM_NAME": "Gadai Pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 15,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gadhaipura",
  "Area": 147613.789529,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 83,
  "SLUM_NAME": "New Colony two",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 16,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 23508.190196,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 84,
  "SLUM_NAME": "New Colony one",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 16,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 21502.759776,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 85,
  "SLUM_NAME": "Chandanpura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 16,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 25564.710077,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 86,
  "SLUM_NAME": "Resham mill basti",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 16,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 14149.485534,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 87,
  "SLUM_NAME": "Anand Nagar (Chamda mill)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 17,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 22454.762635,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 88,
  "SLUM_NAME": " Ara mill ( Harijan basti)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 17,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 6145.849033,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 89,
  "SLUM_NAME": " 3v colony Lal quater",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 17,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 9736.450545,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 90,
  "SLUM_NAME": " New kanch mill",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 17,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 10282.356079,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 91,
  "SLUM_NAME": " Adarsh nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 18,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Jaderua Kalah",
  "Area": 24029.696667,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 92,
  "SLUM_NAME": " Rushalpur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 18,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Jaderua Kalah",
  "Area": 8210.92936,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 93,
  "SLUM_NAME": "Jaderua Kalah",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 19,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Jaderua Kalah",
  "Area": 55382.830598,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 94,
  "SLUM_NAME": "Rachana Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 19,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Jaderua Khurd",
  "Area": 23878.971715,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 95,
  "SLUM_NAME": "Vivek Nagar ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 21,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 33024.159344,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 96,
  "SLUM_NAME": "Panchsheel Nagar ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 21,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 27031.15202,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 97,
  "SLUM_NAME": "Mella Dulpur ",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 21,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 31707.951974,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 98,
  "SLUM_NAME": " Santi nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 21,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 2382.975921,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 99,
  "SLUM_NAME": " Bagiya hanuman nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 21,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 31632.029356,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 100,
  "SLUM_NAME": "Basti Godham",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 19696.603116,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 101,
  "SLUM_NAME": "Shidheshwar Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 11256.305461,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 102,
  "SLUM_NAME": " Khaleefa colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 2556.110385,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 103,
  "SLUM_NAME": " Gopalpura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 4523.467085,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 104,
  "SLUM_NAME": " Shidarth nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 5233.866461,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 105,
  "SLUM_NAME": "Nadi Par Tal",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 23,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 15178.743984,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 106,
  "SLUM_NAME": " Galla kothar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 23,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 26518.674779,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 107,
  "SLUM_NAME": " Ambedkar nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 23,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 4592.47123,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 108,
  "SLUM_NAME": " Shri nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 23,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 73547.020049,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 109,
  "SLUM_NAME": " Harijan basti",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 23,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 2889.932219,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 110,
  "SLUM_NAME": " Leather fectory",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 25,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 20671.346242,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 111,
  "SLUM_NAME": " Sheetla colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 25,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 28353.621231,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 112,
  "SLUM_NAME": "Tikinoya morar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 17720.111528,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 113,
  "SLUM_NAME": "Harijan basti Harijan gurudwara",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 6902.616471,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 114,
  "SLUM_NAME": "Khateek mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 6575.0602,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 115,
  "SLUM_NAME": "Hanuman colony morar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Jaderua Kalah",
  "Area": 4625.93532,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 116,
  "SLUM_NAME": "Tyagi nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 17339.055019,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 117,
  "SLUM_NAME": "Peetal karkhana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 13780.333435,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 118,
  "SLUM_NAME": " Kacheri parusram",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 5881.912651,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 119,
  "SLUM_NAME": " Vinay colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Bahodapur",
  "Area": 6636.040123,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 120,
  "SLUM_NAME": " Ghass mandi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 26,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 2744.052421,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 121,
  "SLUM_NAME": "Ram nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 27,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 13858.109536,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 122,
  "SLUM_NAME": "HarnamPura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 28,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 21246.341211,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 123,
  "SLUM_NAME": "Bheem nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 28,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 30941.865528,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 124,
  "SLUM_NAME": "Phule nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 28,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 32318.361795,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 125,
  "SLUM_NAME": "Kumharapura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 28,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Morar",
  "Area": 31913.120048,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 126,
  "SLUM_NAME": "Mahal gaon (Karouli mata)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 29,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mahal gaon",
  "Area": 214255.452017,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 127,
  "SLUM_NAME": "Gujrati Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 31,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ghospura",
  "Area": 6156.306359,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 128,
  "SLUM_NAME": "Laxmanpura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 31,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mahal gaon",
  "Area": 22400.534516,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 129,
  "SLUM_NAME": "Mari mata",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 32,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Ahukhana khurd",
  "Area": 30530.138653,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 130,
  "SLUM_NAME": "Mahal gaon ( Mari mata)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 32,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Ahukhana khurd",
  "Area": 11731.435155,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 131,
  "SLUM_NAME": "Ravi das nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 16717.473014,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 132,
  "SLUM_NAME": " Dongarpur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 12608.334059,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 133,
  "SLUM_NAME": "Laxman taliya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 7735.850645,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 134,
  "SLUM_NAME": " Khateek mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5440.472185,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 135,
  "SLUM_NAME": " Khalasipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 25965.157807,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 136,
  "SLUM_NAME": " Piyau wali gali",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 33,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 6015.869533,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 137,
  "SLUM_NAME": " Pardi mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 34,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 14458.284931,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 138,
  "SLUM_NAME": "Shekh Ki Bagiya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 22487.128913,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 139,
  "SLUM_NAME": "Swarnrekha Nala Jiwaji Ganj",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 18926.384568,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 140,
  "SLUM_NAME": "Subey Ki Goth",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 16503.329483,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 141,
  "SLUM_NAME": "Santi Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11597.667587,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 142,
  "SLUM_NAME": " Rassi wala mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 15390.568804,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 143,
  "SLUM_NAME": "Daliya wala mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 1712.747729,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 144,
  "SLUM_NAME": " Ganj wala mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 35,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5268.10132,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 145,
  "SLUM_NAME": "Dhobi ghat no .2",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 36,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 10924.859098,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 146,
  "SLUM_NAME": " Dhobi ghat no .1",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 36,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 3580.704698,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 147,
  "SLUM_NAME": " Bakra mandi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 36,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5872.118065,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 148,
  "SLUM_NAME": " Satya narayan ki tekri",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 36,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11492.09152,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 149,
  "SLUM_NAME": "Madhou Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 71883.363349,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 150,
  "SLUM_NAME": "Sanjay Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 173874.883896,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 151,
  "SLUM_NAME": "Nimbaji ki kho",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 295782.387078,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 152,
  "SLUM_NAME": " Naya pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 5453.549577,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 153,
  "SLUM_NAME": "Jagriti nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 41507.670542,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 154,
  "SLUM_NAME": " Titurima colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 5785.383826,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 155,
  "SLUM_NAME": " Shati nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 3201.201496,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 156,
  "SLUM_NAME": " Aman ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 37,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 8127.341472,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 157,
  "SLUM_NAME": "Gol pahadiya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 16994.93106,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 158,
  "SLUM_NAME": "Gupteswar Pahadi",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 54399.238316,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 159,
  "SLUM_NAME": "Amra Pahad",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 43553.536469,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 160,
  "SLUM_NAME": "Raja gas godam",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 41296.679058,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 161,
  "SLUM_NAME": "Ganesh mandir raja gas godam",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 95616.039651,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 162,
  "SLUM_NAME": "Harkota",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 100494.589374,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 163,
  "SLUM_NAME": "Bhinyo ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 36146.894091,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 164,
  "SLUM_NAME": "Lal kuwar ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 28535.859016,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 165,
  "SLUM_NAME": " Mehra sahab ki talaiya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 38,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 9976.854119,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 166,
  "SLUM_NAME": "Kambal Kendra harizan Basti",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 39,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 9463.561933,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 167,
  "SLUM_NAME": "Sath bhai ki goth",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 39,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 11302.114063,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 168,
  "SLUM_NAME": "Jatar gali Swarnrekha Nala",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 39,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 31965.995726,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 169,
  "SLUM_NAME": "Dholi bua ka pull",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 39,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 19472.143618,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 170,
  "SLUM_NAME": " Bai sahab ki pared",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 39,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 8841.990831,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 171,
  "SLUM_NAME": " Bhure baba ki basti",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 40,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 15295.902565,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 172,
  "SLUM_NAME": "Gadi wala mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 40,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 6484.402496,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 173,
  "SLUM_NAME": "Bheisha chokey",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 40,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 2339.704338,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 174,
  "SLUM_NAME": " Tope wala mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 41,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 50925.714567,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 175,
  "SLUM_NAME": "Khurja Wala Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 44,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11259.217105,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 176,
  "SLUM_NAME": " Jatavpura  (Lalitpur colony )",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 45,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Lalitpur",
  "Area": 9181.90657,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 177,
  "SLUM_NAME": "Tappu Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 46,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 34753.32583,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 178,
  "SLUM_NAME": "Teli ki Bazariya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 46,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11469.244012,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 179,
  "SLUM_NAME": "Kamati Pura Jatav Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 47,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 30607.083138,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 180,
  "SLUM_NAME": "Kabuter Ki Hath",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 47,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 13820.845106,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 181,
  "SLUM_NAME": " Roxy pull lakade khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 47,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11575.292687,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 182,
  "SLUM_NAME": " Utar khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 47,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5350.704525,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 183,
  "SLUM_NAME": " Kadam sahab ka bada",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 48,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 4494.853015,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 184,
  "SLUM_NAME": " Jambur khana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 48,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 8762.620452,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 185,
  "SLUM_NAME": " Hem singh ki pared",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 48,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 8852.884829,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 186,
  "SLUM_NAME": " Haidar ganj",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 48,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 6829.806686,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 187,
  "SLUM_NAME": " Aapa ganj (Karigaro ka mohalla )",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 48,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5882.772382,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 188,
  "SLUM_NAME": " Hari anna ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 49,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 8492.533608,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 189,
  "SLUM_NAME": " Banjara saha ka nalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 49,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 12394.076447,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 190,
  "SLUM_NAME": " Kala saiyad",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 49,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 8414.749696,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 191,
  "SLUM_NAME": " Nayapura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 49,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Kota lashkar",
  "Area": 5590.319708,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 192,
  "SLUM_NAME": "Imali naka",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 51,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 20665.727822,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 193,
  "SLUM_NAME": "Jatav mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 51,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 8585.953762,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 194,
  "SLUM_NAME": "Sikandar kampu",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 51,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 27969.679939,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 195,
  "SLUM_NAME": "Apa ganj  (Hathi khana)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 51,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 29578.896734,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 196,
  "SLUM_NAME": "Gudi naka",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 52,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 13415.949919,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 197,
  "SLUM_NAME": "Pyaga",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 52,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 83093.636918,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 198,
  "SLUM_NAME": "Nadariya wali Mata",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 52,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 311080.719936,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 199,
  "SLUM_NAME": " Gudi upar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 52,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 174068.86,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 200,
  "SLUM_NAME": " Bilgaiya ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 52,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 14084.547091,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 201,
  "SLUM_NAME": " Lakarkhana",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 9608.704782,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 202,
  "SLUM_NAME": "Munshiyon ka mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 13910.21988,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 203,
  "SLUM_NAME": "Dev Nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 5685.902229,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 204,
  "SLUM_NAME": "Karwari Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 6476.947399,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 205,
  "SLUM_NAME": "Nayapura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 11910.760637,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 206,
  "SLUM_NAME": "Engale ki goth",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 7951.182008,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 207,
  "SLUM_NAME": "Ganjiwala Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 10364.842325,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 208,
  "SLUM_NAME": "Pan patte ki goth",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 9679.331634,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 209,
  "SLUM_NAME": "Rishi nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 6428.555932,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 210,
  "SLUM_NAME": "Surya nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 53,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 7623.001508,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 211,
  "SLUM_NAME": " Harijan basti ( Jawahar colony)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 54,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 4250.575824,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 212,
  "SLUM_NAME": " Army ki bajriya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 54,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 2646.527592,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 213,
  "SLUM_NAME": " Chana kothar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 54,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 4531.347154,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 214,
  "SLUM_NAME": "Awadpura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 55,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 23445.60159,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 215,
  "SLUM_NAME": " khajanchi Baba",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 55,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Gudhi",
  "Area": 151977.207255,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 216,
  "SLUM_NAME": "Mudia Pahad",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 43215.697284,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 217,
  "SLUM_NAME": "Gade Wala Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 21936.852738,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 218,
  "SLUM_NAME": "Pardi Mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 40518.789915,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 219,
  "SLUM_NAME": " Gnji Kho ( gali No. 1)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 33731.792918,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 220,
  "SLUM_NAME": " Labhed pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 3853.981703,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 221,
  "SLUM_NAME": " Naka chandra badni  (Gali no. 2,4,5)",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 13233.175476,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 222,
  "SLUM_NAME": " Dev nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 56,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 43689.453475,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 223,
  "SLUM_NAME": "Of ki Bagiya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 57,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Lalitpur",
  "Area": 20967.426615,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 224,
  "SLUM_NAME": " Ranipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 57,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Lalitpur",
  "Area": 13895.460418,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 225,
  "SLUM_NAME": "Nirdhan nagar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 58,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "City lashkar",
  "Area": 34735.61183,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 226,
  "SLUM_NAME": "Labhad Pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 28834.797853,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 227,
  "SLUM_NAME": "Vicky Factory",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mahal gaon",
  "Area": 27438.948876,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 228,
  "SLUM_NAME": "Laliya Pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Laliya Pura",
  "Area": 48763.727563,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 229,
  "SLUM_NAME": "Khoti Gao",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Keadarpur",
  "Area": 38190.991606,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 230,
  "SLUM_NAME": "Badee Mareaya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Keadarpur",
  "Area": 18080.80096,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 231,
  "SLUM_NAME": "Choti Madiya",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Keadarpur",
  "Area": 30588.387467,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 232,
  "SLUM_NAME": " Neem chandoha",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Neem chandoha",
  "Area": 30030.277372,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 233,
  "SLUM_NAME": " Pardi mohallla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 59,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mudhiya pahad",
  "Area": 6943.293896,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 234,
  "SLUM_NAME": " Marghat bali phadri",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Mahal gaon",
  "Area": 159242.597458,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 235,
  "SLUM_NAME": "Cotey ki saray",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Bhatkhadi",
  "Area": 22096.675435,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 236,
  "SLUM_NAME": " Hurawali",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 81424.865948,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 237,
  "SLUM_NAME": "Harkheda",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Mehara",
  "Area": 50432.869897,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 238,
  "SLUM_NAME": "Dongarpur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Dongarpur",
  "Area": 31270.572894,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 239,
  "SLUM_NAME": " Sirol colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Sirol",
  "Area": 30462.65412,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 240,
  "SLUM_NAME": " New mehara colony",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Mehara",
  "Area": 129912.050777,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 241,
  "SLUM_NAME": " Alapur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": " Alapur",
  "Area": 25787.137818,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 242,
  "SLUM_NAME": " Ohadpur",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": " Ohadpur",
  "Area": 40040.716081,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 243,
  "SLUM_NAME": " Ghosipura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NON-NOTIFIED",
  "VILLAGE": "Gram Morar",
  "Area": 18920.946873,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 244,
  "SLUM_NAME": " Bale ka pura",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 60,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "Guda",
  "Area": 66760.183541,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 245,
  "SLUM_NAME": " Kasai mohalla",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 14,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "NOT_KNOWN",
  "Area": 4159.054417,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 246,
  "SLUM_NAME": " Ashok Colony Morar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 22,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "NOT_KNOWN",
  "Area": 12174.512512,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 247,
  "SLUM_NAME": " Roshani Ghar",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 57,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "NOT_KNOWN",
  "Area": 3927.072712,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 248,
  "SLUM_NAME": " Nimvalker Ki Gothe",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 46,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "NOT_KNOWN",
  "Area": 4238.31148,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 },
 {
  "SLUM_ID": 249,
  "SLUM_NAME": "Guda",
  "STATE_CODE": "UP",
  "DIST_CODE": "UP01",
  "CITY_TOWN_NAME": "GWALIOR",
  "WARD_NO": 55,
  "SLUM_TYPE": "NOTIFIED",
  "VILLAGE": "NOT_KNOWN",
  "Area": 49917.004686,
  "LAND_OWNERSHIP": "",
  "TOTAL_HOUSE_HOLDS": ""
 }
]